title: Testujemy Just-the-docs
description: Pierwsze kroki z Just-the-docs!
theme: just-the-docs

url: https://AlicjaJot.github.io/The-ultimate-guide-to-remote-work

aux_links:
  Template Repository: https://github.com/AlicjaJot/The-ultimate-guide-to-remote-work/
